name: .NET Core Build with Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      config: 'Release'

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "3.1.x"

    - name: Install dependencies
      run: dotnet restore "./server/Uno"

    - name: Build
      run: dotnet build --configuration $config --no-restore "./server/Uno"

    - name: Test
      run: dotnet test "./server/Uno"